export const questions = [
    {question: "",
    isYesNo: true,
    },
    {question: "",
    isYesNo: false,
    },
    {question: "Have you ever felt uncomfortable around someone due to their skin color?",
    isYesNo: false,
    },
    {question: "Have you made jokes about your own culture or someone else’s’?",
    isYesNo: false,
    },
    {question: "Have you ever accused anyone of playing the race card when they talk about their achievements or struggles?",
    isYesNo: false,
    },
    {question: "Do you get offended or attacked when someone accuses you of being racist?",
    isYesNo: false,
    },
    {question: "Have you ever laughed at or overlooked a joke that someone else has made about someone’s skin color/race/culture?",
    isYesNo: false,
    },
    {question: "Have you felt indifferent towards the current racial climate?",
    isYesNo: false,
    },
    {question: "Do you believe that the presence of Asian immigrants in your country decreases your chances of finding a job?",
    isYesNo: false,
    },
    {question: "Do you think Asians are a marginalized group?",
    isYesNo: false,
    },
    {question: "Do you believe that Asian people are genetically smarter than other races?",
    isYesNo: false,
    },
    {question: "Do you believe that POCs need to conform to the culture/practices/values of the country they currently live in?",
    isYesNo: true,
    },
    {question: "Have you asked yourself if you are racist?",
    isYesNo: true,
    },
    {question: "Have you read a book, watched a film or attended an event on the experiences of marginalized groups in the past year?",
    isYesNo: true,
    },
    {question: "Have you taken a minute to recognize your own privilege whether that be your gender, race, social standing or sexual orientation?",
    isYesNo: true,
    },
    {question: "In the past year, have you had an uncomfortable conversation lately about race or your own personal biases? Ie. with your company, school, friends or family",
    isYesNo: true,
    },
    {question: "Have you attempted to advocate for marginalized communities?",
    isYesNo: true,
    },  
]
